### ISSUE TITLE
'site/' does not appear to be a mkdocs build directory!

### ISSUE THREAD

**Issue by berot3** [CTXz/mkauthdocs#1]
I get the following error:
`'site/' does not appear to be a mkdocs build directory!`

I did everything as instructed.

But I guess mkauthdocs is not alive anymore?

**Comment by CTXz** [comment]
Its always alive, it's just that I haven't used it myself for quite a while now! I'll take a look at it once I find the time.

Thanks for reporting.

**Comment by CTXz** [comment]
The issue should no longer persist with 4a325fe098cd9b8007d5ba413df9b1bfc35be617 . The PyPI package has also been updated.
