### ISSUE TITLE
mkdocs gh-deploy changing php back to html

### ISSUE THREAD

**Issue by amuchoudhary** [CTXz/mkauthdocs#3]
mkdocs                             1.3.0
mkdocs-material                    7.1.0
mkdocs-material-extensions         1.0.3

##building using mkdocs 
$ `mkdocs build`
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory:/path-to-my-micro-site/site
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
              - index.md
INFO     -  Documentation built in 0.39 seconds

##integrating login mechanism
$ `mkauthdocs administrator admin ./site`
The above command changes some files inside site directory to php extension as expected
./index.php
./404.php
./login.php
./home/home/index.php

###Now the issue occurs when we push this build to github
$` mkdocs gh-deploy`
**INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /path-to-my-micro-site/site**
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
              - index.md
INFO     -  Documentation built in 0.37 seconds
INFO     -  Copying '/path-to-my-micro-site/site' to 'gh-pages' branch and pushing to GitHub.
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 12 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 326 bytes | 326.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/********/*****************.git
   afefefac..324413413  gh-pages -> gh-pages
INFO     -  Your documentation should be available shortly.

As we can see, the stdout of gh-deploy command shows, it is building the site again before pushing, so our changes done are actually ignored. 
Is there any way we can append gh-deploy action in mkauthdocs so that the authenticated site is directly pushed to github. It would be of great value addition

**Comment by CTXz** [comment]
Interesting, I must admit that I've never used the gh-deploy function, thus the lack of compatibility with it was completely oblivious to me.

I'll take a look at it once I find some spare time.

Thanks for the issue!

**Comment by amuchoudhary** [comment]
Hey, by the way GitHubPages didn't support php code as they are built for
static pages only. This tool is perfect example of **sober simple tool**.
Thanks for all your time and support.
And about the issue, I just commented out the line in gh-deploy.py where
the build function was called and the issue was resolved.
